# Use JDK 17 as the base image
FROM adoptopenjdk:17-jre-hotspot

# Set the working directory within the container
WORKDIR /app

# Copy the executable JAR file from your local machine to the container
COPY target/Employee-0.0.1-SNAPSHOT.jar app.jar

# Define the command to run your Spring Boot application
CMD ["java", "-jar", "app.jar"]
